# Generated by Django 3.0.4 on 2020-05-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('paassword', models.CharField(max_length=20)),
                ('datacheck', models.IntegerField(null=True)),
            ],
        ),
    ]
