# Generated by Django 3.0.4 on 2020-05-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginform',
            old_name='paassword',
            new_name='password',
        ),
    ]
