# Generated by Django 3.0.4 on 2020-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpwd', models.CharField(max_length=20)),
                ('newpwd', models.CharField(max_length=20)),
                ('conpwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='loginform',
            name='uname',
            field=models.EmailField(max_length=50),
        ),
    ]
