# Generated by Django 3.0.4 on 2020-05-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20200527_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginform',
            name='uname',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
