# Generated by Django 3.0.4 on 2020-05-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20200528_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginForm',
            new_name='LoginPage',
        ),
    ]
